spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-64.railway.app:7530/course
    username: postgres
    password: SZao7PtcmAWlnTlA9UuZ
flyway:

  url: jdbc:postgresql://containers-us-west-64.railway.app:7530/course

  user: postgres

  password: SZao7PtcmAWlnTlA9UuZ

  enabled: true

  baselineOnMigrate: true

  locations:

    - 'classpath:db/migration'